PRAGMA foreign_keys=OFF;

DROP TABLE IF EXISTS PRODUTO;
DROP TABLE IF EXISTS MARCA;
DROP TABLE IF EXISTS DEPARTAMENTO;
DROP TABLE IF EXISTS COMPRA;
DROP TABLE IF EXISTS ESTOQUE;
DROP TABLE IF EXISTS SAIDA;

PRAGMA foreign_keys=ON;

CREATE TABLE MARCA(
    ID INTEGER CONSTRAINT PK_MARCA PRIMARY KEY AUTOINCREMENT NOT NULL,
    NOME VARCHAR(521) UNIQUE,
    EMPRESA VARCHAR(521) NOT NULL
);
CREATE TABLE DEPARTAMENTO(
    ID INTEGER CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY AUTOINCREMENT NOT NULL,
    NOME VARCHAR(521) UNIQUE
);
CREATE TABLE PRODUTO(
    ID INTEGER CONSTRAINT PK_PRODUTO PRIMARY KEY AUTOINCREMENT NOT NULL,
    NOME VARCHAR(521) NOT NULL,
    ID_MARCA INTEGER NOT NULL,
    ID_DEPT INTEGER NOT NULL, 
    CONSTRAINT FK_DEPARTAMENTO FOREIGN KEY(ID_DEPT) REFERENCES DEPARTAMENTO(ID),
    CONSTRAINT FK_MARCA FOREIGN KEY (ID_MARCA) REFERENCES MARCA(ID)
);
CREATE TABLE COMPRA(
    ID INTEGER CONSTRAINT PK_COMPRA PRIMARY KEY AUTOINCREMENT NOT NULL,
    PRECO DOUBLE NOT NULL,
    DT DATE NOT NULL,
    QUANTIDADE INTEGER NOT NULL,
    TOTAL INTEGER NOT NULL,
    ID_PRODUTO INTEGER NOT NULL,
    CONSTRAINT FK_PRODUTO FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(ID)
);
CREATE TABLE SAIDA(
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    DT DATE NOT NULL,
    QUANTIDADE INTEGER NOT NULL,
    ID_COMPRA INTEGER NOT NULL,
    ID_PRODUTO INTEGER NOT NULL,
    CONSTRAINT FK_COMPRA FOREIGN KEY(ID_COMPRA) REFERENCES COMPRA(ID),
    CONSTRAINT FK_PRODUTO FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(ID)
);